project:
  type: website

website:
  title: "El sitio de reportes de Lalo"
  navbar:
    left:
      - text: "Sobre este sitio de PRUEBA"
        href: index.qmd  # SIEMPRE debe tener un archivo index.qmd
  sidebar:
    style: docked
    contents:
      - index.qmd
      - section: "Primer reporte SENCILLO"
        contents:
          - mis_reportes/reporte-01.qmd
      - section: "Segundo reporte OTRA VEZ SENCILLO"
        contents:
          - mis_reportes/reporte-02.qmd
      - section: "Último reporte SIMPLE"
        contents:
          - mis_reportes/reporte-03.qmd

      - section: "Combinación Reportes R y Python"
        contents:
          - mis_reportes/reporte-04.qmd

format:
  html:
    theme: sandstone
    toc: true
    lang: es
